name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=22.2.2
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - wandb
